swagger: '2.0'
info:
  title: example
  version: 0.0.0
paths:
  /items:
    get:
      responses:
        200:
          description: items
      security:
      - OauthSecurity:
        - read
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://accounts.google.com/o/oauth2/auth
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    scopes:
      read: read items
