application: goapp-scaffold
version: 1
runtime: go
api_version: go1
threadsafe: true

instance_class: F1
automatic_scaling:
  max_idle_instances: 1

default_expiration: 10m

handlers:
# Static assets
# swagger-ui
- url: /swagger-ui(.*)/
  static_files: ../swagger-ui/dist\1/index.html
  upload: /swagger-ui(.*)/index.html
- url: /swagger-ui(.*)
  static_files: ../swagger-ui/dist\1
  upload: /swagger-ui(.*)
- url: /swagger-ui/
  static_dir: ../swagger-ui/dist

- url: /.*
  script: _go_app

nobuild_files:
- vendor

skip_files:
- |
  ^(.*/)?(
  (#.*#)|
  (.*\.mapping)|
  (.*\.po)|
  (.*\.pot)|
  (.*\.py[co])|
  (.*\.sw?)|
  (.*\.yaml)|
  (.*_test\.go)|
  (.*~)|
  (LICENSE)|
  (Makefile.*)|
  (\..*)|
  (vendor/.*)|
  )$
