application: appid
version: 1
runtime: go
api_version: go1
threadsafe: true

handlers:
# Static assets
#- url: /_static
#  static_dir: static
- url: /_ah/spi/.*
  script: _go_app
- url: /.*
  script: _go_app
